name: WakacaW Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: |
          if [ -f ./gradlew ]; then
            chmod +x ./gradlew
          fi

      - name: Build Debug APK
        run: |
          if [ -f ./gradlew ]; then
            ./gradlew assembleDebug
          else
            gradle assembleDebug
          fi

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WakacaW-Kernel-Manager
          path: app/build/outputs/apk/debug/*.apk

